# settings
screen_width, screen_height = 1600, 900
fps = 60
n = 50  # length of list
x0, xn = 1, screen_width  # [x0, xn]
y = screen_height
distance = xn / n
width = distance - 1
delay = 0
done = True
sort = True
mainloop = True
pause = True
first_start = True
text_size = 32
menu_text_size = 40
j = 1
k = 0
c = 0
s = 0
